### ISSUE TITLE
ModelMultipleChoiceField with CheckBoxSelectMultiple

### ISSUE THREAD

**Issue by Lutando** [WiserTogether/django-remote-forms#19]
If I have a form in forms.py

class SomeForm(forms.Form):
    some_var = ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,queryset=SomeModel.objects.all())

The multiple selects are not captured when converting a filled form to a RemoteForm() object only the last select is captured

**Comment by Laotanling** [comment]
HI ,had you set your init validation?
